### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Boyceman** [wanglian/workbase-server#1]
hello there,
when i input `sudo reboot` after fun `sudo snap run --shell workbase-server`, output this `bash: /usr/bin/sudo: Permission denied`

**Comment by wanglian** [comment]
You need to exit the shell before`sudo reboot`.
```
$ sudo snap run --shell workbase-server
# echo ROOT_URL=https://example.com > $SNAP_COMMON/root-url.env
# exit
$ sudo reboot
```
Thanks for the report! I'll update the doc.

**Comment by Boyceman** [comment]
Yep, thanks very much.😊
